# Generated by Django 3.1.6 on 2021-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_connect', '0002_auto_20210220_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='algname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='backtest',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
