# Generated by Django 3.1.6 on 2021-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_connect', '0003_auto_20210221_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='filepath',
            field=models.CharField(max_length=200),
        ),
    ]
