# Generated by Django 3.1.6 on 2021-02-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quant_connect', '0004_auto_20210221_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtest',
            name='buytol',
        ),
        migrations.RemoveField(
            model_name='backtest',
            name='selltol',
        ),
    ]
