# Generated by Django 3.1.6 on 2021-02-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_connect', '0005_auto_20210221_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtest',
            name='filepath',
            field=models.CharField(max_length=1000),
        ),
    ]
