# Generated by Django 3.1.6 on 2021-03-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant_connect', '0006_auto_20210228_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backtest',
            old_name='filepath',
            new_name='orig_filepath',
        ),
        migrations.AddField(
            model_name='backtest',
            name='new_filepath',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
